// This file is automatically generated. Do not modify it manually.

export const firebaseConfig = {
  "apiKey": "AIzaSyAkqSX3Gp1fm_IWlY95hnko0Qd6BUoJKs8",
  "authDomain": "adlure-2dn00.firebaseapp.com",
  "projectId": "adlure-2dn00",
  "storageBucket": "adlure-2dn00.appspot.com",
  "messagingSenderId": "545249681440",
  "appId": "1:545249681440:web:a1b2c3d4e5f6a1b2c3d4e5"
};
