// This file is automatically generated. Do not modify it manually.

export const firebaseConfig = {
  "apiKey": "mock-api-key",
  "authDomain": "adlure-2dn00.firebaseapp.com",
  "projectId": "adlure-2dn00",
  "storageBucket": "adlure-2dn00.appspot.com",
  "messagingSenderId": "112233445566",
  "appId": "1:112233445566:web:a1b2c3d4e5f6a1b2c3d4e5"
};
